services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    expose:
      - "80"
    networks:
      - shopping-cart-network

  api:
    image: registry.gitlab.com/saysimpler/hiring/fe-sample-api
    container_name: api
    expose:
      - "8080"
    networks:
      - shopping-cart-network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "${SHOPPING_CART_PORT:-8081}:80"
    volumes:
      - ./nginx/conf.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - api
    networks:
      - shopping-cart-network

networks:
  shopping-cart-network:
